var card_data = [
    /* Blessings */
	{
        "count": 1,
        "color": "ciba",
        "title": "",
        "icon": "ciba",
        "icon_back": "ciba",
        "contents": [
            "subtitle | Blessing",
            "rule",
			"property | Duration | time",
			"property | Activation | at will/Immediate",
			"property | Condition | requirements",
			"rule",
            "text | <br>",
			"text | DO STUFF.",
			"text | <br>",
			"rule",
			"subtitle | Grace/Occult",
			"property | Secret Effect | <i>Do not share with other players.</i>",
			"text | <br>",
			"text | DO SECRET STUFF",
			"text | <br>",
			"rule",
			"text | <i>add that flava flave.</i>",
        ]
    },
	{
        "count": 1,
        "color": "ciba",
        "title": "",
        "icon": "ciba",
        "icon_back": "ciba",
        "contents": [
            "subtitle | Blessing",
            "rule",
			"property | Duration | time",
			"property | Activation | at will/Immediate",
			"property | Condition | requirements",
			"rule",
            "text | <br>",
			"text | DO STUFF.",
			"text | <br>",
			"rule",
			"subtitle | Grace/Occult",
			"property | Secret Effect | <i>Do not share with other players.</i>",
			"text | <br>",
			"text | DO SECRET STUFF",
			"text | <br>",
			"rule",
			"text | <i>add that flava flave.</i>",
        ]
    },
	{
        "count": 1,
        "color": "ciba",
        "title": "",
        "icon": "ciba",
        "icon_back": "ciba",
        "contents": [
            "subtitle | Blessing",
            "rule",
			"property | Duration | time",
			"property | Activation | at will/Immediate",
			"property | Condition | requirements",
			"rule",
            "text | <br>",
			"text | DO STUFF.",
			"text | <br>",
			"rule",
			"subtitle | Grace/Occult",
			"property | Secret Effect | <i>Do not share with other players.</i>",
			"text | <br>",
			"text | DO SECRET STUFF",
			"text | <br>",
			"rule",
			"text | <i>add that flava flave.</i>",
        ]
    },
	/* Favor */
	{
        "count": 1,
        "color": "ciba",
        "title": "Come at Me, Bro",
        "icon": "ciba",
        "icon_back": "ciba",
        "contents": [
            "subtitle | Favor",
            "rule",
			"property | Duration | 10 minutes",
			"property | Activation | At will",
			"property | Condition | Challenging target to duel",
			"rule",
            "text | <br>",
			"text | Gain advantage on persuasion checks used to challenge someone to duel or to convince someone to partake in a duel.",
			"text | <br>",
			"rule",
			"text | <i>Fight me irl faggot ill fuck you up i swer on me mum.</i>",
        ]
    },
	{
        "count": 1,
        "color": "ciba",
        "title": "",
        "icon": "ciba",
        "icon_back": "ciba",
        "contents": [
            "subtitle | Favor",
            "rule",
			"property | Duration | time",
			"property | Activation | At will",
			"property | Condition | Knowledge of target",
			"rule",
            "text | <br>",
			"text | DO STUFF.",
			"text | <br>",
			"rule",
			"subtitle | Grace/Occult",
			"property | Secret Effect | <i>Do not share with other players.</i>",
			"text | <br>",
			"text | DO SECRET STUFF",
			"text | <br>",
			"rule",
			"text | <i>add that flava flave.</i>",
        ]
    },
	{
        "count": 1,
        "color": "ciba",
        "title": "",
        "icon": "ciba",
        "icon_back": "ciba",
        "contents": [
            "subtitle | Favor",
            "rule",
			"property | Duration | time",
			"property | Activation | At will",
			"property | Condition | requirements",
			"rule",
            "text | <br>",
			"text | DO STUFF.",
			"text | <br>",
			"rule",
			"subtitle | Grace/Occult",
			"property | Secret Effect | <i>Do not share with other players.</i>",
			"text | <br>",
			"text | DO SECRET STUFF",
			"text | <br>",
			"rule",
			"text | <i>add that flava flave.</i>",
        ]
    },
	/* Intervention */
	{
        "count": 1,
        "color": "ciba",
        "title": "",
        "icon": "ciba",
        "icon_back": "ciba",
        "contents": [
            "subtitle | Intervention",
            "rule",
			"property | Duration | time",
			"property | Activation | At will",
			"property | Condition | requirements",
			"rule",
            "text | <br>",
			"text | DO STUFF.",
			"text | <br>",
			"rule",
			"subtitle | Grace/Occult",
			"property | Secret Effect | <i>Do not share with other players.</i>",
			"text | <br>",
			"text | DO SECRET STUFF",
			"text | <br>",
			"rule",
			"text | <i>add that flava flave.</i>",
        ]
    },
	{
        "count": 1,
        "color": "ciba",
        "title": "",
        "icon": "ciba",
        "icon_back": "ciba",
        "contents": [
            "subtitle | Intervention",
            "rule",
			"property | Duration | time",
			"property | Activation | At will",
			"property | Condition | requirements",
			"rule",
            "text | <br>",
			"text | DO STUFF.",
			"text | <br>",
			"rule",
			"subtitle | Grace/Occult",
			"property | Secret Effect | <i>Do not share with other players.</i>",
			"text | <br>",
			"text | DO SECRET STUFF",
			"text | <br>",
			"rule",
			"text | <i>add that flava flave.</i>",
        ]
    },
	{
        "count": 1,
        "color": "ciba",
        "title": "Siege Engineer",
        "icon": "ciba",
        "icon_back": "ciba",
        "contents": [
            "subtitle | Intervention",
            "rule",
			"property | Duration | 12 hours",
			"property | Activation | Operate a siege engine.",
			"property | Condition | N/A",
			"rule",
            "text | <br>",
			"text | Gain advantage to all checks related to operating and preparing seige engines for 12 hours.",
			"text | <br>",
			"rule",
			"subtitle | Occult",
			"property | Secret Effect | <i>Do not share with other players.</i>",
			"text | <br>",
			"text | You feel the flame of Ciba in your heart. Don't let the enemy escape or surrender!",
			"text | <br>",
			"rule",
			"text | <i>These machines are finely tuned tools of widespread destruction.</i>",
        ]
    },
	
	/* Miracle */
	{
        "count": 1,
        "color": "ciba",
        "title": "",
        "icon": "ciba",
        "icon_back": "ciba",
        "contents": [
            "subtitle | Miracle",
            "rule",
			"property | Duration | time",
			"property | Activation | At will",
			"property | Condition | requirements",
			"rule",
            "text | <br>",
			"text | DO STUFF.",
			"text | <br>",
			"rule",
			"subtitle | Grace/Occult",
			"property | Secret Effect | <i>Do not share with other players.</i>",
			"text | <br>",
			"text | DO SECRET STUFF",
			"text | <br>",
			"rule",
			"text | <i>add that flava flave.</i>",
        ]
    },
];
