var card_data = [
	/* Blessings */
	{
        "count": 1,
        "color": "lust",
        "title": "Fake-Out",
        "icon": "lust",
        "icon_back": "lust",
        "contents": [
            "subtitle | Blessing",
            "rule",
			"property | Duration | 14 days (1/day)",
			"property | Activation | Immediate",
			"property | Condition | Wielding shield and either a lance, spear, or sword.",
			"rule",
            "text | <br>",
			"text | If you would miss with a melee weapon attack, you can choose to fake-out instead. Roll an off-hand melee attack roll with your shield, at advantage.",
			"text | <br>",
			"rule",
			"subtitle | Grace/Occult",
			"property | Secret Effect | <i>Do not share with other players.</i>",
			"text | <br>",
			"text | The effect goes here. Here is how you are affected.",
			"text | <br>",
			"rule",
			"text | <i>I have perfected the art of missing you. You stand no chance against me.</i>",
        ]
    },
	{
        "count": 1,
        "color": "lust",
        "title": "Grace of Lust",
        "icon": "lust",
        "icon_back": "lust",
        "contents": [
            "subtitle | Blessing",
            "rule",
			"property | Duration | days",
			"property | Activation | trigger/At Will/Immediate",
			"property | Condition | Attacking with a weapon that has reach.",
			"rule",
            "text | <br>",
            "text | You can make an attack with a weapon that has reach as though it has finesse instead.",
			"text | <br>",
			"rule",
			"subtitle | Grace",
			"property | Secret Effect | <i>Do not share with other players.</i>",
			"text | <br>",
			"text | The effect goes here. Here is how you are affected.",
			"text | <br>",
			"rule",
			"text | <i>Flavor. Add a bit of flair to that card.</i>",
        ]
    },
	{
        "count": 1,
        "color": "lust",
        "title": "",
        "icon": "lust",
        "icon_back": "lust",
        "contents": [
            "subtitle | Blessing",
            "rule",
			"property | Duration | days",
			"property | Activation | trigger/At Will/Immediate",
			"rule",
            "text | <br>",
            "text | The effect of the card goes here. This card affects people.",
			"text | <br>",
			"rule",
			"subtitle | Grace/Occult",
			"property | Secret Effect | <i>Do not share with other players.</i>",
			"text | <br>",
			"text | The effect goes here. Here is how you are affected.",
			"text | <br>",
			"rule",
			"text | <i>Flavor. Add a bit of flair to that card.</i>",
        ]
    },
	
	/* Favors */
	{
        "count": 1,
        "color": "lust",
        "title": "Lucky Strike",
        "icon": "lust",
        "icon_back": "lust",
        "contents": [
            "subtitle | Favor",
            "rule",
			"property | Duration | Instant",
			"property | Activation | At will",
			"property | Condition | Attacking with a weapon with reach",
			"rule",
            "text | <br>",
            "text | If you are attacking with a weapon that has reach, you gain advantage. You get +1 to damage.",
			"text | If you fail to hit, this card is not discarded.",
			"text | <br>",
			"rule",
			"subtitle | Grace/Occult",
			"property | Secret Effect | <i>Do not share with other players.</i>",
			"text | <br>",
			"text | You become interested in doing extra research of Lust and her combat styles. Finding books to read is ideal.",
			"text | <br>",
			"rule",
			"text | <i>Just swing your weapon. Maybe you'll hit them.</i>",
        ]
    },
	{
        "count": 1,
        "color": "lust",
        "title": "",
        "icon": "lust",
        "icon_back": "lust",
        "contents": [
            "subtitle | Favor",
            "rule",
			"property | Duration | days",
			"property | Activation | trigger/At Will/Immediate",
			"rule",
            "text | <br>",
            "text | The effect of the card goes here. This card affects people.",
			"text | <br>",
			"rule",
			"subtitle | Grace/Occult",
			"property | Secret Effect | <i>Do not share with other players.</i>",
			"text | <br>",
			"text | The effect goes here. Here is how you are affected.",
			"text | <br>",
			"rule",
			"text | <i>Flavor. Add a bit of flair to that card.</i>",
        ]
    },
	{
        "count": 1,
        "color": "lust",
        "title": "",
        "icon": "lust",
        "icon_back": "lust",
        "contents": [
            "subtitle | Favor",
            "rule",
			"property | Duration | days",
			"property | Activation | trigger/At Will/Immediate",
			"rule",
            "text | <br>",
            "text | The effect of the card goes here. This card affects people.",
			"text | <br>",
			"rule",
			"subtitle | Grace/Occult",
			"property | Secret Effect | <i>Do not share with other players.</i>",
			"text | <br>",
			"text | The effect goes here. Here is how you are affected.",
			"text | <br>",
			"rule",
			"text | <i>Flavor. Add a bit of flair to that card.</i>",
        ]
    },
	
	/* Interventions */
	{
        "count": 1,
        "color": "lust",
        "title": "Wild Stance",
        "icon": "lust",
        "icon_back": "lust",
        "contents": [
            "subtitle | Intervention",
            "rule",
			"property | Duration | 10 minutes",
			"property | Activation | Next attack roll",
			"property | Condition | Attack with a lance, spear, or sword",
			"rule",
            "text | <br>",
            "text | Gain advantage on all attack rolls with this weapon for 10 minutes.",
			"text | <br>",
			"rule",
			"text | <i>All the training in the world means nothing against a man whose trained the same. Yet, a wild-strike could be the thing that catches them off-guard.</i>",
        ]
    },
	{
        "count": 1,
        "color": "lust",
        "title": "",
        "icon": "lust",
        "icon_back": "lust",
        "contents": [
            "subtitle | Intervention",
            "rule",
			"property | Duration | days",
			"property | Activation | trigger/At Will/Immediate",
			"rule",
            "text | <br>",
            "text | The effect of the card goes here. This card affects people.",
			"text | <br>",
			"rule",
			"subtitle | Grace/Occult",
			"property | Secret Effect | <i>Do not share with other players.</i>",
			"text | <br>",
			"text | The effect goes here. Here is how you are affected.",
			"text | <br>",
			"rule",
			"text | <i>Flavor. Add a bit of flair to that card.</i>",
        ]
    },
	{
        "count": 1,
        "color": "lust",
        "title": "",
        "icon": "lust",
        "icon_back": "lust",
        "contents": [
            "subtitle | Intervention",
            "rule",
			"property | Duration | days",
			"property | Activation | trigger/At Will/Immediate",
			"rule",
            "text | <br>",
            "text | The effect of the card goes here. This card affects people.",
			"text | <br>",
			"rule",
			"subtitle | Grace/Occult",
			"property | Secret Effect | <i>Do not share with other players.</i>",
			"text | <br>",
			"text | The effect goes here. Here is how you are affected.",
			"text | <br>",
			"rule",
			"text | <i>Flavor. Add a bit of flair to that card.</i>",
        ]
    },
	
	/* Miracles */
	{
        "count": 1,
        "color": "lust",
        "title": "Mercy!",
        "icon": "lust",
        "icon_back": "lust",
        "contents": [
            "subtitle | Type: Miracle",
            "rule",
			"property | Duration | 24 hours",
			"property | Activation | At will against creature with CR lower than your level (3/month)",
			"rule",
            "text | <br>",
            "text | Any time you would deal attack damage to a creature with a CR lower than your level, you can choose to show mercy instead.",
			"text | If you would have killed the creature, had you not shown mercy, the creature must make a DC 10+damage WIS saving throw. On failure, the creature is charmed by you. It will take combat orders for you for 24 hours.",
			"text | You may only charm 1 creature at a time through Mercy.",
			"text | <br>",
			"rule",
			"text | <i>Flavor. Add a bit of flair to that card.</i>",
        ]
    },
];
