var card_data = [
    /* Blessings */
	{
        "count": 1,
        "color": "god",
        "title": "",
        "icon": "god",
        "icon_back": "god",
        "contents": [
            "subtitle | Blessing",
            "rule",
			"property | Duration | time",
			"property | Activation | at will/Immediate",
			"property | Condition | requirements",
			"rule",
            "text | <br>",
			"text | DO STUFF.",
			"text | <br>",
			"rule",
			"subtitle | Grace/Occult",
			"property | Secret Effect | <i>Do not share with other players.</i>",
			"text | <br>",
			"text | DO SECRET STUFF",
			"text | <br>",
			"rule",
			"text | <i>add that flava flave.</i>",
        ]
    },
	{
        "count": 1,
        "color": "god",
        "title": "",
        "icon": "god",
        "icon_back": "god",
        "contents": [
            "subtitle | Blessing",
            "rule",
			"property | Duration | time",
			"property | Activation | at will/Immediate",
			"property | Condition | requirements",
			"rule",
            "text | <br>",
			"text | DO STUFF.",
			"text | <br>",
			"rule",
			"subtitle | Grace/Occult",
			"property | Secret Effect | <i>Do not share with other players.</i>",
			"text | <br>",
			"text | DO SECRET STUFF",
			"text | <br>",
			"rule",
			"text | <i>add that flava flave.</i>",
        ]
    },
	{
        "count": 1,
        "color": "god",
        "title": "",
        "icon": "god",
        "icon_back": "god",
        "contents": [
            "subtitle | Blessing",
            "rule",
			"property | Duration | time",
			"property | Activation | at will/Immediate",
			"property | Condition | requirements",
			"rule",
            "text | <br>",
			"text | DO STUFF.",
			"text | <br>",
			"rule",
			"subtitle | Grace/Occult",
			"property | Secret Effect | <i>Do not share with other players.</i>",
			"text | <br>",
			"text | DO SECRET STUFF",
			"text | <br>",
			"rule",
			"text | <i>add that flava flave.</i>",
        ]
    },
	/* Favor */
	{
        "count": 1,
        "color": "god",
        "title": "",
        "icon": "god",
        "icon_back": "god",
        "contents": [
            "subtitle | Favor",
            "rule",
			"property | Duration | time",
			"property | Activation | At will",
			"property | Condition | requirements",
			"rule",
            "text | <br>",
			"text | DO STUFF.",
			"text | <br>",
			"rule",
			"subtitle | Grace/Occult",
			"property | Secret Effect | <i>Do not share with other players.</i>",
			"text | <br>",
			"text | DO SECRET STUFF",
			"text | <br>",
			"rule",
			"text | <i>add that flava flave.</i>",
        ]
    },
	{
        "count": 1,
        "color": "god",
        "title": "",
        "icon": "god",
        "icon_back": "god",
        "contents": [
            "subtitle | Favor",
            "rule",
			"property | Duration | time",
			"property | Activation | At will",
			"property | Condition | requirements",
			"rule",
            "text | <br>",
			"text | DO STUFF.",
			"text | <br>",
			"rule",
			"subtitle | Grace/Occult",
			"property | Secret Effect | <i>Do not share with other players.</i>",
			"text | <br>",
			"text | DO SECRET STUFF",
			"text | <br>",
			"rule",
			"text | <i>add that flava flave.</i>",
        ]
    },
	{
        "count": 1,
        "color": "god",
        "title": "",
        "icon": "god",
        "icon_back": "god",
        "contents": [
            "subtitle | Favor",
            "rule",
			"property | Duration | time",
			"property | Activation | At will",
			"property | Condition | requirements",
			"rule",
            "text | <br>",
			"text | DO STUFF.",
			"text | <br>",
			"rule",
			"subtitle | Grace/Occult",
			"property | Secret Effect | <i>Do not share with other players.</i>",
			"text | <br>",
			"text | DO SECRET STUFF",
			"text | <br>",
			"rule",
			"text | <i>add that flava flave.</i>",
        ]
    },
	/* Intervention */
	{
        "count": 1,
        "color": "god",
        "title": "",
        "icon": "god",
        "icon_back": "god",
        "contents": [
            "subtitle | Intervention",
            "rule",
			"property | Duration | time",
			"property | Activation | At will",
			"property | Condition | requirements",
			"rule",
            "text | <br>",
			"text | DO STUFF.",
			"text | <br>",
			"rule",
			"subtitle | Grace/Occult",
			"property | Secret Effect | <i>Do not share with other players.</i>",
			"text | <br>",
			"text | DO SECRET STUFF",
			"text | <br>",
			"rule",
			"text | <i>add that flava flave.</i>",
        ]
    },
	{
        "count": 1,
        "color": "god",
        "title": "",
        "icon": "god",
        "icon_back": "god",
        "contents": [
            "subtitle | Intervention",
            "rule",
			"property | Duration | time",
			"property | Activation | At will",
			"property | Condition | requirements",
			"rule",
            "text | <br>",
			"text | DO STUFF.",
			"text | <br>",
			"rule",
			"subtitle | Grace/Occult",
			"property | Secret Effect | <i>Do not share with other players.</i>",
			"text | <br>",
			"text | DO SECRET STUFF",
			"text | <br>",
			"rule",
			"text | <i>add that flava flave.</i>",
        ]
    },
	{
        "count": 1,
        "color": "god",
        "title": "",
        "icon": "god",
        "icon_back": "god",
        "contents": [
            "subtitle | Intervention",
            "rule",
			"property | Duration | time",
			"property | Activation | At will",
			"property | Condition | requirements",
			"rule",
            "text | <br>",
			"text | DO STUFF.",
			"text | <br>",
			"rule",
			"subtitle | Grace/Occult",
			"property | Secret Effect | <i>Do not share with other players.</i>",
			"text | <br>",
			"text | DO SECRET STUFF",
			"text | <br>",
			"rule",
			"text | <i>add that flava flave.</i>",
        ]
    },
	/* Miracle */
	{
        "count": 1,
        "color": "god",
        "title": "Second Life",
        "icon": "god",
        "icon_back": "god",
        "contents": [
            "subtitle | Miracle",
            "rule",
			"property | Duration | time",
			"property | Activation | At will",
			"property | Condition | requirements",
			"rule",
            "text | <br>",
			"text | Next time you would die, instead, don't.",
			"text | <br>",
			"rule",
			"subtitle | Grace/Occult",
			"property | Secret Effect | <i>Do not share with other players.</i>",
			"text | <br>",
			"text | DO SECRET STUFF",
			"text | <br>",
			"rule",
			"text | <i>add that flava flave.</i>",
        ]
    },
];
